server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        # Usamos la URL pública con SNI configurado para evitar el error SSL 80
        proxy_pass https://backend-production-4e5e.up.railway.app;
        
        proxy_ssl_server_name on;
        proxy_ssl_name backend-production-4e5e.up.railway.app;
        proxy_set_header Host backend-production-4e5e.up.railway.app;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Tiempos de espera
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
